/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_dkp;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Sayid
 */
public class GUI_TA extends javax.swing.JFrame {

    /**
     * Creates new form GUI_TA
     */
    public GUI_TA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Steam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Rank = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Game = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Uang = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username Steam");

        Steam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SteamActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        Rank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Rank...", "Herald", "Guardian", "Crusader", "Archon", "Legend", "Ancient", "Divine" }));
        Rank.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RankItemStateChanged(evt);
            }
        });
        Rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankActionPerformed(evt);
            }
        });

        jLabel3.setText("Rank");

        Game.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Berapa kali Menang...", "5 Menang", "10 Menang", "Naik Rank" }));
        Game.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                GameItemStateChanged(evt);
            }
        });
        Game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameActionPerformed(evt);
            }
        });

        jLabel4.setText("Game");

        jLabel5.setText("JOKI MMR DOTA2");

        jLabel6.setText("Harga");

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Masukkan Uang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Rank, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Steam, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(Uang))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Steam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rank, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Game, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Uang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(jButton2))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankActionPerformed
       
    }//GEN-LAST:event_RankActionPerformed

    private void RankItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RankItemStateChanged

    }//GEN-LAST:event_RankItemStateChanged

    private void SteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SteamActionPerformed

    private void GameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameActionPerformed
    
        

        
    }//GEN-LAST:event_GameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Steam.setText("");
        Pass.setText("");
        Uang.setText("");
        Harga.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_GameItemStateChanged
             String itemSelected = Game.getSelectedItem().toString();
        
       double hargaitem = 0;
        String RankSelected = Rank.getSelectedItem().toString();
        if (RankSelected.equals("Herald"))
        {
            if (itemSelected.equals("5 Menang"))
                {
                hargaitem = 5;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("10 Menang"))
                {
                hargaitem = 7;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("Naik Rank"))
            {
                hargaitem = 8;
                Harga.setText ("$" + hargaitem);
            }
        }
        else if (RankSelected.equals("Guardian"))
        {
            if (itemSelected.equals("5 Menang"))
                {
                hargaitem = 6;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("10 Menang"))
                {
                hargaitem = 8;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("Naik Rank"))
            {
                hargaitem = 9;
                Harga.setText ("$" + hargaitem);
            }
        }
        else if (RankSelected.equals("Crusader"))
        {
            if (itemSelected.equals("5 Menang"))
                {
                hargaitem = 7;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("10 Menang"))
                {
                hargaitem = 9;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("Naik Rank"))
            {
                hargaitem = 11;
                Harga.setText ("$" + hargaitem);
            }
        }
        else if (RankSelected.equals("Archon"))
        {
            if (itemSelected.equals("5 Menang"))
                {
                hargaitem = 8;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("10 Menang"))
                {
                hargaitem = 10;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("Naik Rank"))
            {
                hargaitem = 13;
                Harga.setText ("$" + hargaitem);
            }
        }
        else if (RankSelected.equals("Legend"))
        {
            if (itemSelected.equals("5 Menang"))
                {
                hargaitem = 15;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("10 Menang"))
                {
                hargaitem = 19;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("Naik Rank"))
            {
                hargaitem = 23;
                Harga.setText ("$" + hargaitem);
            }
        }
        else if (RankSelected.equals("Ancient"))
        {
            if (itemSelected.equals("5 Menang"))
                {
                hargaitem = 25;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("10 Menang"))
                {
                hargaitem = 30;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("Naik Rank"))
            {
                hargaitem = 50;
                Harga.setText ("$" + hargaitem);
            }
        }
        else if (RankSelected.equals("Divine"))
        {
            if (itemSelected.equals("5 Menang"))
                {
                hargaitem = 60;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("10 Menang"))
                {
                hargaitem = 75;
                Harga.setText ("$" + hargaitem);
                }
            else if (itemSelected.equals("Naik Rank"))
            {
                hargaitem = 90;
                Harga.setText ("$" + hargaitem);
            }
        }
    }//GEN-LAST:event_GameItemStateChanged

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        
         for (int i = 1; i <= 2; i ++)
        {
            if (i == 1) 
            {Submit submit = new Submit ();
                JOptionPane.showMessageDialog(null, submit.cetak() + "\n" + submit.cetak1() + "\n" + "Terima Kasih", "Information", JOptionPane.INFORMATION_MESSAGE);
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Silahkan Datang Kembali", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_TA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Game;
    private javax.swing.JLabel Harga;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JComboBox<String> Rank;
    private javax.swing.JTextField Steam;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField Uang;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
